### ISSUE TITLE
Issues with Anaconda

### ISSUE THREAD

**Issue by vgoliber** [opencv-pg/opencv-pg#12]
When installed on a Mac using Anaconda, user saw the following error message when trying to run ```opencvpg``` from command line after pip install.

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/opencvpg/bin/opencvpg", line 8, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/envs/opencvpg/lib/python3.8/site-packages/opencv_pg/launcher.py", line 86, in main
    run_playground(args)
  File "/usr/local/anaconda3/envs/opencvpg/lib/python3.8/site-packages/opencv_pg/launcher.py", line 27, in run_playground
    m = MainWindow(img_path, args.no_docs, args.disable_info_widgets)
  File "/usr/local/anaconda3/envs/opencvpg/lib/python3.8/site-packages/opencv_pg/main.py", line 16, in __init__
    playground.Playground(img_path, no_docs, disable_info_widgets))
  File "/usr/local/anaconda3/envs/opencvpg/lib/python3.8/site-packages/opencv_pg/views/playground.py", line 29, in __init__
    self.setOrientation(Qt.Orientation.Horizontal)
AttributeError: type object 'Orientation' has no attribute 'Horizontal'

**Comment by geoff-va** [comment]
Can you please post a pip freeze?

**Comment by vgoliber** [comment]
[opencvpgana.pip_freeze.txt](https://github.com/opencv-pg/opencv-pg/files/5630586/opencvpgana.pip_freeze.txt)
